let currentPage = 1; // বর্তমান পেজ
const imagesPerPage = 500; // প্রতি পেজে কত ছবি দেখানো হবে
let selectedTags = []; // নির্বাচিত ট্যাগগুলি সংরক্ষণ করবে
const images = [
{"src":"images/People at Work (online) (11)_16.webp","tags":["Looking","Computer","Relaxed","Sitting","Boy","Talking","Girl","Enjoy","People∞"]},
{"src":"images/People at Work (online) (11)_17.webp","tags":["Looking","Front","Boy","Girl","Happy","People∞"]},
{"src":"images/People at Work (online) (11)_18.webp","tags":["Looking","Front","Boy","Girl","People∞"]},
{"src":"images/People at Work (online) (12)_1.webp","tags":["Looking","Front","Boy","Girl","People∞"]},
{"src":"images/People at Work (online) (12)_10.webp","tags":["Looking","Front","People1","Working","Standing","Boy","Talking","shopping"]},
{"src":"images/People at Work (online) (12)_11.webp","tags":["Looking","Side‍","People1","Working","Standing","Boy","Back","shopping"]},
{"src":"images/People at Work (online) (12)_12.webp","tags":["Looking","Front","People1","Confidence","Standing","Boy","Talking","Happy","idea"]},
{"src":"images/People at Work (online) (12)_13.webp","tags":["Looking","Front","People1","Confidence","Standing","Boy"]},
{"src":"images/People at Work (online) (12)_14.webp","tags":["Looking","Front","People1","Relaxed","Working","Sitting","Boy"]},
{"src":"images/People at Work (online) (12)_15.webp","tags":["Looking","Front","People1","Confidence","Relaxed","Working","Standing","Boy","Talking","shopping"]},
{"src":"images/People at Work (online) (12)_16.webp","tags":["Looking","Front","People1","Thinking","Computer","Relaxed","Sitting","Boy"]},
{"src":"images/People at Work (online) (12)_17.webp","tags":["Looking","Side‍","People1","Confused","Computer","Boy","Thinking"]},
{"src":"images/People at Work (online) (12)_18.webp","tags":["Looking","Front","People1","Boy","Travel"]},
{"src":"images/People at Work (online) (12)_2.webp","tags":["Looking","Front","People1","Standing","Boy","See"]},
{"src":"images/People at Work (online) (12)_3.webp","tags":["Looking","Front","People1","Surprising","Standing","Boy","Talking","Angry"]},
{"src":"images/People at Work (online) (12)_4.webp","tags":["Looking","Front","People1","Working","Standing","Boy","shopping"]},
{"src":"images/People at Work (online) (12)_5.webp","tags":["Looking","Old","Front","People1","Loser","Working","Standing","Boy"]},
{"src":"images/People at Work (online) (12)_6.webp","tags":["Looking","Front","People1","Working","Standing","Boy"]},
{"src":"images/People at Work (online) (12)_7.webp","tags":["Looking","Front","People1","Working","Standing","Boy"]},
{"src":"images/People at Work (online) (12)_8.webp","tags":["Looking","Old","Front","People1","Working","Standing","Boy"]},
{"src":"images/People at Work (online) (12)_9.webp","tags":["Looking","Front","People1","Working","Standing","Boy","Travel","shopping"]},
{"src":"images/People at Work (online) (13)_1.webp","tags":["Looking","Front","People2","Surprising","Working","Sitting","Boy","See"]},
{"src":"images/People at Work (online) (13)_10.webp","tags":["Looking","Front","Surprising","Standing","Boy","Girl"]},
{"src":"images/People at Work (online) (13)_11.webp","tags":["Looking","Side‍","People1","Boy"]},
{"src":"images/People at Work (online) (13)_12.webp","tags":["Looking","Side‍","Front","People1","Working","Boy"]},
{"src":"images/People at Work (online) (13)_13.webp","tags":["Looking","Side‍","Front","People1","Working","Boy"]},
{"src":"images/People at Work (online) (13)_14.webp","tags":["Looking","Side‍","Front","People1","Loser","Working","Boy"]},
{"src":"images/People at Work (online) (13)_15.webp","tags":["Looking","Side‍","People1","Boy","Back"]},
{"src":"images/People at Work (online) (13)_16.webp","tags":["Looking","People1","Working","Boy"]},
{"src":"images/People at Work (online) (13)_17.webp","tags":["Looking","Front","Working","Standing","Boy","People∞"]},
{"src":"images/People at Work (online) (13)_18.webp","tags":["Looking","People1","Computer","Working","Boy"]},
{"src":"images/People at Work (online) (13)_2.webp","tags":["Looking","Front","People2","Computer","Working","Sitting","Boy"]},
{"src":"images/People at Work (online) (13)_3.webp","tags":["Looking","Front","Standing","Boy","Happy","People3"]},
{"src":"images/People at Work (online) (13)_4.webp","tags":["Looking","Front","Confused","Standing","Sitting","Boy","Talking","Girl","People3"]},
{"src":"images/People at Work (online) (13)_5.webp","tags":["Looking","Front","Confused","Relaxed","Standing","Sitting","Boy","Girl","People∞"]},
{"src":"images/People at Work (online) (13)_6.webp","tags":["Looking","Front","People1","Boy","Happy"]},
{"src":"images/People at Work (online) (13)_7.webp","tags":["Looking","Front","People1","Boy","Girl","Happy"]},
{"src":"images/People at Work (online) (13)_8.webp","tags":["Looking","Front","People1","Boy"]},
{"src":"images/People at Work (online) (13)_9.webp","tags":["Looking","Front","Standing","Boy","Girl","Happy"]},
{"src":"images/People at Work (online) (14)_1.webp","tags":["Looking","Old","Front","People1","Working","Standing","Boy"]},
{"src":"images/People at Work (online) (14)_10.webp","tags":["Looking","Side‍","Front","People1","Working","Boy"]},
{"src":"images/People at Work (online) (14)_11.webp","tags":["Looking","Side‍","People1","Working","Boy","Searching"]},
{"src":"images/People at Work (online) (14)_12.webp","tags":["Looking","Old","Front","People1","Standing","Boy"]},
{"src":"images/People at Work (online) (14)_13.webp","tags":["Looking","Side‍","Front","People1","Standing","Boy"]},
{"src":"images/People at Work (online) (14)_14.webp","tags":["Looking","Old","Front","People1","Confidence","Standing","Boy"]},
{"src":"images/People at Work (online) (14)_15.webp","tags":["Looking","Side‍","People2","Sitting","Talking","Girl"]},
{"src":"images/People at Work (online) (14)_17.webp","tags":["Looking","Side‍","Front","People2","Standing","Boy","Talking","Angry"]},
{"src":"images/People at Work (online) (14)_2.webp","tags":["Looking","Front","People1","Working","Standing","Boy","Enjoy","Happy"]},
{"src":"images/People at Work (online) (14)_3.webp","tags":["Looking","Front","People1","Working","Boy"]},
{"src":"images/People at Work (online) (14)_4.webp","tags":["Looking","Front","People1","Working","Standing","Boy","Girl","Searching"]},
{"src":"images/People at Work (online) (14)_5.webp","tags":["Looking","Side‍","Front","People1","Standing","Boy"]},
{"src":"images/People at Work (online) (14)_6.webp","tags":["Looking","Front","People1","Loser","Working","Boy","See"]},
{"src":"images/People at Work (online) (14)_7.webp","tags":["Looking","Front","People1","Confidence","Sitting","Boy"]},
{"src":"images/People at Work (online) (14)_8.webp","tags":["Looking","Side‍","People1","Working","Boy"]},
{"src":"images/People at Work (online) (14)_9.webp","tags":["Looking","Side‍","People1","Working","Boy"]},
{"src":"images/People at Work (online) (15)_1.webp","tags":["Looking","Old","Side‍","People2","Standing","Boy","Talking"]},
{"src":"images/People at Work (online) (15)_10.webp","tags":["Looking","Front","People1","Computer","Working","Sitting","Talking","Girl","Enjoy","Happy"]},
{"src":"images/People at Work (online) (15)_11.webp","tags":["Looking","Side‍","People1","Computer","Working","Sitting","Boy"]},
{"src":"images/People at Work (online) (15)_12.webp","tags":["Looking","Front","People1","Computer","Relaxed","Working","Sitting","Boy","Happy"]},
{"src":"images/People at Work (online) (15)_13.webp","tags":["Looking","People1","Computer","Working","Sitting","Boy"]},
{"src":"images/People at Work (online) (15)_14.webp","tags":["Looking","Side‍","People1","Computer","Working","Sitting","Boy"]},
{"src":"images/People at Work (online) (15)_15.webp","tags":["Looking","Front","People1","Boy","Happy"]},
{"src":"images/People at Work (online) (15)_16.webp","tags":["Looking","Old","Front","People1","Boy"]},
{"src":"images/People at Work (online) (15)_17.webp","tags":["Looking","People1","Computer","Working","Sitting","Boy"]},
{"src":"images/People at Work (online) (15)_18.webp","tags":["Looking","Side‍","Front","People2","Computer","Working","Sitting","Boy"]},
{"src":"images/People at Work (online) (15)_3.webp","tags":["Looking","Old","Side‍","People2","Standing","Boy","Talking","Girl"]},
{"src":"images/People at Work (online) (15)_5.webp","tags":["Looking","Old","Side‍","People2","Surprising","Standing","Boy","Talking","Girl"]},
{"src":"images/People at Work (online) (15)_7.webp","tags":["Looking","People2","Sitting","Talking","Girl","shopping"]},
{"src":"images/People at Work (online) (15)_8.webp","tags":["Looking","People2","Sitting","Talking","Girl","shopping"]},
{"src":"images/People at Work (online) (15)_9.webp","tags":["Looking","Front","People1","Computer","Relaxed","Working","Sitting","Boy","Talking","Enjoy","Happy"]},
{"src":"images/People at Work (online) (16)_1.webp","tags":["Looking","Side‍","People1","Working","Boy","Happy","Searching"]},
{"src":"images/People at Work (online) (16)_10.webp","tags":["Looking","Working","Sitting","Boy","Talking","Happy","People∞"]},
{"src":"images/People at Work (online) (16)_11.webp","tags":["Looking","Computer","Working","Sitting","Boy","Talking","Happy","People∞"]},
{"src":"images/People at Work (online) (16)_12.webp","tags":["Looking","Front","Working","Boy","Talking","People∞"]},
{"src":"images/People at Work (online) (16)_13.webp","tags":["Looking","Side‍","People2","Confused","Boy","Talking"]},
{"src":"images/People at Work (online) (16)_14.webp","tags":["Looking","Front","Boy","Talking"]},
{"src":"images/People at Work (online) (16)_15.webp","tags":["Looking","Side‍","Front","People1","Standing","Boy","Talking","See"]},
{"src":"images/People at Work (online) (16)_16.webp","tags":["Looking","Side‍","Front","People1","Boy"]},
{"src":"images/People at Work (online) (16)_17.webp","tags":["Looking","Side‍","Front","People1","Boy"]},
{"src":"images/People at Work (online) (16)_18.webp","tags":["Looking","Front","People1","Sitting","Boy"]},
{"src":"images/People at Work (online) (16)_2.webp","tags":["Looking","Side‍","People2","Computer","Working","Sitting","Boy","Talking"]},
{"src":"images/People at Work (online) (16)_3.webp","tags":["Looking","Front","People2","Working","Sitting","Boy","Talking"]},
{"src":"images/People at Work (online) (16)_4.webp","tags":["Looking","People2","Computer","Working","Sitting","Boy","Talking","Happy"]},
{"src":"images/People at Work (online) (16)_5.webp","tags":["Looking","People2","Working","Sitting","Boy","Talking"]},
{"src":"images/People at Work (online) (16)_6.webp","tags":["Looking","Side‍","Working","Sitting","Boy","Talking"]},
{"src":"images/People at Work (online) (16)_7.webp","tags":["Looking","Front","Working","Boy","Talking"]},
{"src":"images/People at Work (online) (16)_8.webp","tags":["Looking","Working","Boy","Talking","People∞"]},
{"src":"images/People at Work (online) (16)_9.webp","tags":["Looking","Working","Sitting","Boy","Talking","Happy","People∞"]},
{"src":"images/People at Work (online) (17)_1.webp","tags":["Looking","Front","People1","Standing","Boy","See"]},
{"src":"images/People at Work (online) (17)_10.webp","tags":["Looking","Front","People1","Confidence","Standing","Boy"]},
{"src":"images/People at Work (online) (17)_11.webp","tags":["Looking","Front","People1","Working","Standing","Boy"]},
{"src":"images/People at Work (online) (17)_12.webp","tags":["Looking","Front","People1","Confidence","Standing","Boy"]},
{"src":"images/People at Work (online) (17)_13.webp","tags":["Looking","Front","People1","Standing","Boy"]},
{"src":"images/People at Work (online) (17)_14.webp","tags":["Looking","Front","People1","Working","Standing","Boy"]},
{"src":"images/People at Work (online) (17)_15.webp","tags":["Looking","Front","People1","Boy"]},
{"src":"images/People at Work (online) (17)_16.webp","tags":["Looking","Front","People1","Standing","Boy"]},
{"src":"images/People at Work (online) (17)_2.webp","tags":["Looking","Side‍","People1","Working","Boy"]},
{"src":"images/People at Work (online) (17)_3.webp","tags":["Looking","Front","People1","Boy","Talking"]},
{"src":"images/People at Work (online) (17)_4.webp","tags":["Looking","Side‍","People2","Working","Boy"]},
{"src":"images/People at Work (online) (17)_5.webp","tags":["Looking","Front","People1","Boy"]},
{"src":"images/People at Work (online) (17)_6.webp","tags":["Looking","Front","People1","Boy"]},
{"src":"images/People at Work (online) (17)_7.webp","tags":["Looking","Front","People1","Standing","Boy"]},
{"src":"images/People at Work (online) (17)_8.webp","tags":["Looking","Front","People1","Standing","Boy"]},
{"src":"images/People at Work (online) (17)_9.webp","tags":["Looking","Front","People1","Standing","Boy","Happy"]},
{"src":"images/People Basic (1)_10.webp","tags":["Looking","Front","People1","Standing","Girl"]},
{"src":"images/People Basic (1)_11.webp","tags":["Looking","Front","People1","Standing","Girl"]},
{"src":"images/People Basic (1)_12.webp","tags":["Looking","Front","People1","Standing","Girl"]},
{"src":"images/People Basic (1)_13.webp","tags":["Looking","Front","People1","Standing","Talking","Girl","Enjoy","Happy"]},
{"src":"images/People Basic (1)_14.webp","tags":["Looking","Front","People1","Standing","Boy","Girl"]},
{"src":"images/People Basic (1)_15.webp","tags":["Looking","Front","People1","Standing","Boy","Girl"]},
{"src":"images/People Basic (1)_16.webp","tags":["Looking","Front","People1","Standing","Girl"]},
{"src":"images/People Basic (1)_17.webp","tags":["Looking","Front","People1","Standing","Boy"]},
{"src":"images/People Basic (1)_18.webp","tags":["Looking","Front","People1","Standing","Girl"]},
{"src":"images/People Basic (1)_6.webp","tags":["Looking","Front","People1","Standing","Talking","Girl"]},
{"src":"images/People Basic (1)_7.webp","tags":["Looking","Front","People1","Confidence","Relaxed","Standing","Boy"]},
{"src":"images/People Basic (1)_8.webp","tags":["Looking","Front","People1","Standing","Girl"]},
{"src":"images/People Basic (1)_9.webp","tags":["Looking","Front","People1","Standing","Boy"]},
{"src":"images/People Basic (2)_1.webp","tags":["Looking","Front","People1","Standing","Girl"]},
{"src":"images/People Basic (2)_10.webp","tags":["Looking","Front","People1","Standing","Girl"]},
{"src":"images/People Basic (2)_12.webp","tags":["Looking","Front","People1","Standing","Boy"]},
{"src":"images/People Basic (2)_14.webp","tags":["Looking","Front","People1","Standing","Girl"]},
{"src":"images/People Basic (2)_16.webp","tags":["Looking","Front","People1","Standing","Boy"]},
{"src":"images/People Basic (2)_18.webp","tags":["Looking","Front","People1","Standing","Boy"]},
{"src":"images/People Basic (2)_2.webp","tags":["Looking","Front","People1","Standing","Girl"]},
{"src":"images/People Basic (2)_3.webp","tags":["Looking","Front","People1","Standing","Girl"]},
{"src":"images/People Basic (2)_4.webp","tags":["Looking","Front","People1","Relaxed","Standing","Boy"]},
{"src":"images/People Basic (2)_5.webp","tags":["Looking","Front","People1","Standing","Girl"]},
{"src":"images/People Basic (2)_6.webp","tags":["Looking","Old","Front","People1","Standing","Boy"]},
{"src":"images/People Basic (2)_7.webp","tags":["Looking","Front","People1","Relaxed","Standing","Girl"]},
{"src":"images/People Basic (2)_8.webp","tags":["Looking","Front","People1","Standing","Girl"]},
{"src":"images/People Emotions (online) (10)_1.webp","tags":["Looking","Front","People1","Relaxed","Girl","Enjoy","Happy"]},
{"src":"images/People Emotions (online) (10)_10.webp","tags":["Looking","Front","People1","Standing","Boy"]},
{"src":"images/People Emotions (online) (10)_11.webp","tags":["Looking","Front","People1","Boy"]},
{"src":"images/People Emotions (online) (10)_12.webp","tags":["Looking","Front","People1","Confused","Relaxed","Boy"]},
{"src":"images/People Emotions (online) (10)_13.webp","tags":["Looking","Front","People1","Standing","Boy"]},
{"src":"images/People Emotions (online) (10)_14.webp","tags":["Looking","Front","People1","Girl"]},
{"src":"images/People Emotions (online) (10)_15.webp","tags":["Looking","Front","People1","Standing","Talking","Girl","Happy"]},
{"src":"images/People Emotions (online) (10)_16.webp","tags":["Looking","Front","People1","Relaxed","Girl"]},
{"src":"images/People Emotions (online) (10)_17.webp","tags":["Looking","Front","People1","Loser","Girl"]},
{"src":"images/People Emotions (online) (10)_18.webp","tags":["Looking","Front","People1","Loser","Relaxed","Standing","Girl"]},
{"src":"images/People Emotions (online) (10)_2.webp","tags":["Looking","Front","People1","Talking","Girl","Enjoy","Happy"]},
{"src":"images/People Emotions (online) (10)_3.webp","tags":["Looking","Front","People1","Surprising","Confidence","Standing","Talking","Girl","Enjoy","Happy"]},
{"src":"images/People Emotions (online) (10)_4.webp","tags":["Looking","Front","People1","Girl"]},
{"src":"images/People Emotions (online) (10)_5.webp","tags":["Looking","Front","People1","Relaxed","Girl"]},
{"src":"images/People Emotions (online) (10)_6.webp","tags":["Looking","Front","People1","Confused","Relaxed","Working","Sitting","Girl"]},
{"src":"images/People Emotions (online) (10)_7.webp","tags":["Looking","Front","People1","Boy"]},
{"src":"images/People Emotions (online) (10)_8.webp","tags":["Looking","Front","People1","Boy","Talking","Enjoy","Happy"]},
{"src":"images/People Emotions (online) (10)_9.webp","tags":["Looking","Side‍","People1","Relaxed","Boy"]},
{"src":"images/People Emotions (online) (11)_1.webp","tags":["Looking","Front","People1","Standing","Girl"]},
{"src":"images/People Emotions (online) (11)_10.webp","tags":["Looking","Front","People1","Standing","Girl","Angry"]},
{"src":"images/People Emotions (online) (11)_11.webp","tags":["Looking","Front","People1","Standing","Girl","Angry"]},
{"src":"images/People Emotions (online) (11)_12.webp","tags":["Looking","Front","People1","Computer","Working","Girl","Angry"]},
{"src":"images/People Emotions (online) (11)_13.webp","tags":["Looking","Front","People1","Standing","Girl","Angry"]},
{"src":"images/People Emotions (online) (11)_14.webp","tags":["Looking","Front","People1","Girl"]},
{"src":"images/People Emotions (online) (11)_15.webp","tags":["Looking","Old","Side‍","Front","People1","Standing","Boy","Angry"]},
{"src":"images/People Emotions (online) (11)_16.webp","tags":["Looking","Old","Front","People1","Standing","Boy","Talking","Angry"]},
{"src":"images/People Emotions (online) (11)_17.webp","tags":["Looking","Front","People1","Standing","Girl"]},
{"src":"images/People Emotions (online) (11)_18.webp","tags":["Looking","Front","People1","Standing","Girl"]},
{"src":"images/People Emotions (online) (11)_2.webp","tags":["Looking","Front","People1","Standing","Talking","Girl"]},
{"src":"images/People Emotions (online) (11)_3.webp","tags":["Looking","Front","People1","Girl"]},
{"src":"images/People Emotions (online) (11)_4.webp","tags":["Looking","Front","People1","Computer","Working","Girl"]},
{"src":"images/People Emotions (online) (11)_5.webp","tags":["Looking","Side‍","People1","Relaxed","Girl"]},
{"src":"images/People Emotions (online) (11)_6.webp","tags":["Looking","Front","People1","Girl"]},
{"src":"images/People Emotions (online) (11)_7.webp","tags":["Looking","Front","People1","Computer","Relaxed","Girl"]},
{"src":"images/People Emotions (online) (11)_8.webp","tags":["Looking","Front","People1","Relaxed","Standing","Girl"]},
{"src":"images/People Emotions (online) (11)_9.webp","tags":["Looking","Front","People1","Standing","Girl"]},
{"src":"images/People Emotions (online) (12)_1.webp","tags":["Looking","Front","People1","Standing","Talking","Girl"]},
{"src":"images/People Emotions (online) (12)_10.webp","tags":["Looking","Front","People1","Confused","Computer","Working","Sitting","Girl"]},
{"src":"images/People Emotions (online) (12)_11.webp","tags":["Looking","Front","People1","Surprising","Computer","Working","Talking","Girl"]},
{"src":"images/People Emotions (online) (12)_12.webp","tags":["Looking","Front","People1","Surprising","Computer","Working","Talking","Girl"]},
{"src":"images/People Emotions (online) (12)_13.webp","tags":["Looking","Front","People1","Standing","Boy"]},
{"src":"images/People Emotions (online) (12)_14.webp","tags":["Looking","Front","People1","Surprising","Computer","Working","Boy","Talking","Angry"]},
{"src":"images/People Emotions (online) (12)_15.webp","tags":["Looking","Front","People1","Surprising","Computer","Working","Boy","Talking","Angry"]},
{"src":"images/People Emotions (online) (12)_16.webp","tags":["Looking","Front","People1","Confused","Computer","Working","Boy","Cry"]},
{"src":"images/People Emotions (online) (12)_17.webp","tags":["Looking","Front","People1","Standing","Girl"]},
{"src":"images/People Emotions (online) (12)_18.webp","tags":["Looking","Front","People1","Standing","Girl"]},
{"src":"images/People Emotions (online) (12)_2.webp","tags":["Looking","Front","People1","Computer","Working","Sitting","Girl"]},
{"src":"images/People Emotions (online) (12)_3.webp","tags":["Looking","Front","People1","Standing","Girl"]},
{"src":"images/People Emotions (online) (12)_4.webp","tags":["Looking","Front","People1","Standing","Girl","Angry"]},
{"src":"images/People Emotions (online) (12)_5.webp","tags":["Looking","Front","People1","Confidence","Girl"]},
{"src":"images/People Emotions (online) (12)_6.webp","tags":["Looking","Front","People1","Confidence","Standing","Talking","Girl"]},
{"src":"images/People Emotions (online) (12)_7.webp","tags":["Looking","Front","People1","Surprising","Standing","Talking","Girl","Cry"]},
{"src":"images/People Emotions (online) (12)_8.webp","tags":["Looking","Front","People1","Computer","Working","Sitting","Girl"]},
{"src":"images/People Emotions (online) (12)_9.webp","tags":["Looking","Front","People1","Surprising","Standing","Girl","Angry"]},
{"src":"images/People Emotions (online) (13)_1.webp","tags":["Looking","Front","People1","Standing","Girl"]},
{"src":"images/People Emotions (online) (13)_10.webp","tags":["Looking","Front","People1","Girl"]},
{"src":"images/People Emotions (online) (13)_11.webp","tags":["Front","People1","Girl"]},
{"src":"images/People Emotions (online) (13)_12.webp","tags":["Front","People1","Girl"]},
{"src":"images/People Emotions (online) (13)_13.webp","tags":["Looking","Front","People2","Computer","Working","Sitting","Boy","Girl"]},
{"src":"images/People Emotions (online) (13)_14.webp","tags":["Looking","Front","People1","Standing","Baby"]},
{"src":"images/People Emotions (online) (13)_15.webp","tags":["Side‍","Front","People1","Standing","Boy"]},
{"src":"images/People Emotions (online) (13)_16.webp","tags":["Looking","Front","People1","Standing","Girl","Enjoy","Happy"]},
{"src":"images/People Emotions (online) (13)_17.webp","tags":["Looking","Front","People1","Standing","Girl","Enjoy","Happy"]},
{"src":"images/People Emotions (online) (13)_18.webp","tags":["Looking","Front","People1","Girl"]},
{"src":"images/People Emotions (online) (13)_2.webp","tags":["Looking","Front","People1","Standing","Boy"]},
{"src":"images/People Emotions (online) (13)_3.webp","tags":["Looking","Front","People1","Standing","Boy","Angry"]},
{"src":"images/People Emotions (online) (13)_4.webp","tags":["Looking","Old","Front","People1","Working","Sitting","Boy","Angry"]},
{"src":"images/People Emotions (online) (13)_5.webp","tags":["Looking","Front","People1","Girl"]},
{"src":"images/People Emotions (online) (13)_6.webp","tags":["Looking","Front","People1","Standing","Talking","Girl"]},
{"src":"images/People Emotions (online) (13)_7.webp","tags":["Looking","Front","People1","Loser","Girl"]},
{"src":"images/People Emotions (online) (13)_8.webp","tags":["Looking","Front","People1","Loser","Relaxed","Sitting","Girl"]},
{"src":"images/People Emotions (online) (13)_9.webp","tags":["Looking","Front","People1","Computer","Girl"]},
{"src":"images/People Emotions (online) (14)_1.webp","tags":["Side‍","People1","Loser","Sitting","Girl","Back"]},
{"src":"images/People Emotions (online) (14)_10.webp","tags":["Looking","Front","People1","Standing","Boy","Talking","Enjoy","Happy"]},
{"src":"images/People Emotions (online) (14)_11.webp","tags":["Looking","Front","People1","Standing","Boy","Talking","Enjoy","Happy"]},
{"src":"images/People Emotions (online) (14)_12.webp","tags":["Looking","Front","People1","Confused","Standing","Boy","Talking"]},
{"src":"images/People Emotions (online) (14)_13.webp","tags":["Looking","Front","People1","Standing","Boy","Talking"]},
{"src":"images/People Emotions (online) (14)_14.webp","tags":["Looking","Front","People1","Surprising","Standing","Boy","Cry"]},
{"src":"images/People Emotions (online) (14)_15.webp","tags":["Looking","Front","People1","Standing","Girl"]},
{"src":"images/People Emotions (online) (14)_16.webp","tags":["Looking","Front","People1","Standing","Talking","Girl"]},
{"src":"images/People Emotions (online) (14)_17.webp","tags":["Front","People1","Confused","Standing","Girl"]},
{"src":"images/People Emotions (online) (14)_18.webp","tags":["Front","People1","Confused","Standing","Girl"]},
{"src":"images/People Emotions (online) (14)_2.webp","tags":["Looking","Front","People1","Standing","Girl"]},
{"src":"images/People Emotions (online) (14)_3.webp","tags":["Looking","People1","Standing","Girl"]},
{"src":"images/People Emotions (online) (14)_4.webp","tags":["Looking","People1","Relaxed","Girl"]},
{"src":"images/People Emotions (online) (14)_5.webp","tags":["Looking","Front","People1","Boy"]},
{"src":"images/People Emotions (online) (14)_6.webp","tags":["Looking","Front","People1","Standing","Girl","Enjoy","Happy"]},
{"src":"images/People Emotions (online) (14)_7.webp","tags":["Looking","Front","People1","Standing","Girl"]},
{"src":"images/People Emotions (online) (14)_8.webp","tags":["Looking","Front","People1","Standing","Girl"]},
{"src":"images/People Emotions (online) (14)_9.webp","tags":["Looking","Front","People1","Relaxed","Boy","Talking"]},
{"src":"images/People Emotions (online) (15)_1.webp","tags":["Looking","Front","People1","Standing","Girl"]},
{"src":"images/People Emotions (online) (15)_10.webp","tags":["Looking","Front","People1","Standing","Girl"]},
{"src":"images/People Emotions (online) (15)_11.webp","tags":["Looking","Old","Front","People1","Standing","Girl"]},
{"src":"images/People Emotions (online) (15)_12.webp","tags":["Looking","Old","Front","People1","Standing","Girl"]},
{"src":"images/People Emotions (online) (15)_13.webp","tags":["Looking","Old","Front","People1","Standing","Boy"]},
{"src":"images/People Emotions (online) (15)_14.webp","tags":["Looking","Old","Front","People1","Confused","Standing","Boy"]},
{"src":"images/People Emotions (online) (15)_15.webp","tags":["Looking","Old","Standing","Boy","Girl"]},
{"src":"images/People Emotions (online) (15)_16.webp","tags":["Looking","Old","Front","People1","Standing","Boy"]},
{"src":"images/People Emotions (online) (15)_17.webp","tags":["Looking","Old","Front","People1","Standing","Boy"]},
{"src":"images/People Emotions (online) (15)_18.webp","tags":["Old","Front","People1","Boy"]},
{"src":"images/People Emotions (online) (15)_2.webp","tags":["Looking","Front","People1","Thinking","Confused","Cry"]},
{"src":"images/People Emotions (online) (15)_3.webp","tags":["Looking","Front","People1","Relaxed","Sitting"]},
{"src":"images/People Emotions (online) (15)_4.webp","tags":["Looking","Front","People1","Standing","Girl"]},
{"src":"images/People Emotions (online) (15)_5.webp","tags":["Looking","Front","People1","Standing","Girl"]},
{"src":"images/People Emotions (online) (15)_6.webp","tags":["Looking","Front","People1","Thinking","Standing","Girl"]},
{"src":"images/People Emotions (online) (15)_7.webp","tags":["Looking","Front","People1","Confused","Standing","Girl"]},
{"src":"images/People Emotions (online) (15)_8.webp","tags":["Looking","Old","Front","People1","Standing","Boy"]},
{"src":"images/People Emotions (online) (15)_9.webp","tags":["Looking","Old","Front","People1","Standing","Boy"]},
{"src":"images/People Emotions (online) (16)_1.webp","tags":["Looking","Front","People1","Standing","Boy","Baby"]},
{"src":"images/People Emotions (online) (16)_10.webp","tags":["Looking","Front","People1","Relaxed","Boy"]},
{"src":"images/People Emotions (online) (16)_11.webp","tags":["Looking","Front","People1","Boy"]},
{"src":"images/People Emotions (online) (16)_12.webp","tags":["Looking","Front","People1","Boy"]},
{"src":"images/People Emotions (online) (16)_13.webp","tags":["Looking","Front","People1","Boy"]},
{"src":"images/People Emotions (online) (16)_14.webp","tags":["Looking","Front","People1","Relaxed","Boy"]},
{"src":"images/People Emotions (online) (16)_15.webp","tags":["Looking","Front","People1"]},
{"src":"images/People Emotions (online) (16)_16.webp","tags":["Looking","Front","People1","Girl"]},
{"src":"images/People Emotions (online) (16)_17.webp","tags":["Looking","Old","Front","People1","Boy"]},
{"src":"images/People Emotions (online) (16)_18.webp","tags":["Looking","Old","Front","People1","Boy"]},
{"src":"images/People Emotions (online) (16)_2.webp","tags":["Looking","Front","People1","Standing","Boy","Baby"]},
{"src":"images/People Emotions (online) (16)_3.webp","tags":["Looking","Front","People1","Standing","Boy","Baby"]},
{"src":"images/People Emotions (online) (16)_4.webp","tags":["Looking","Front","People1","Standing","Boy","Baby"]},
{"src":"images/People Emotions (online) (16)_5.webp","tags":["Looking","Front","People1","Girl","Baby"]},
{"src":"images/People Emotions (online) (16)_6.webp","tags":["Looking","Front","People1","Boy"]},
{"src":"images/People Emotions (online) (16)_7.webp","tags":["Looking","Front","People1","Boy"]},
{"src":"images/People Emotions (online) (16)_8.webp","tags":["Looking","Front","People1","Boy"]},
{"src":"images/People Emotions (online) (16)_9.webp","tags":["Looking","Front","People1","Boy"]},
{"src":"images/People Emotions (online) (17)_1.webp","tags":["Looking","Front","People1","Girl"]},
{"src":"images/People Emotions (online) (17)_10.webp","tags":["Looking","Front","Boy","Girl","People3"]},
{"src":"images/People Emotions (online) (17)_11.webp","tags":["Looking","Front","People2","Boy","Talking","Girl","Enjoy","Happy"]},
{"src":"images/People Emotions (online) (17)_12.webp","tags":["Looking","Front","People2","Boy","Talking","Girl","Enjoy","Happy"]},
{"src":"images/People Emotions (online) (17)_13.webp","tags":["Looking","Front","People2","Boy","Talking","Girl"]},
{"src":"images/People Emotions (online) (17)_14.webp","tags":["Looking","Front","People2","Boy","Girl"]},
{"src":"images/People Emotions (online) (17)_15.webp","tags":["Looking","Front","People2","Loser","Boy","Girl"]},
{"src":"images/People Emotions (online) (17)_16.webp","tags":["Looking","Front","People1","Standing","Talking","Girl"]},
{"src":"images/People Emotions (online) (17)_17.webp","tags":["Looking","Front","People1","Standing","Talking","Girl","See"]},
{"src":"images/People Emotions (online) (17)_18.webp","tags":["Looking","People1","Relaxed","Standing","Girl"]},
{"src":"images/People Emotions (online) (17)_2.webp","tags":["Looking","Front","People1","Girl"]},
{"src":"images/People Emotions (online) (17)_3.webp","tags":["Looking","Front","People1","Boy","Girl"]},
{"src":"images/People Emotions (online) (17)_4.webp","tags":["Looking","Front","People1","Relaxed","Boy"]},
{"src":"images/People Emotions (online) (17)_5.webp","tags":["Looking","Front","People1","Boy"]},
{"src":"images/People Emotions (online) (17)_6.webp","tags":["Looking","Front","People1","Loser","Girl"]},
{"src":"images/People Emotions (online) (17)_7.webp","tags":["Looking","Old","Front","People1","Boy","Talking","Cry"]},
{"src":"images/People Emotions (online) (17)_8.webp","tags":["Looking","Front","People1","Surprising","Boy","Angry"]},
{"src":"images/People Emotions (online) (17)_9.webp","tags":["Looking","Front","People2","Boy","Girl"]},
{"src":"images/People Emotions (online) (18)_1.webp","tags":["Looking","Front","People1","Standing","Boy"]},
{"src":"images/People Emotions (online) (18)_10.webp","tags":["Looking","Front","People1","Computer","Working","Sitting","Talking","Girl","Enjoy","Happy"]},
{"src":"images/People Emotions (online) (18)_11.webp","tags":["Looking","Front","People1","Computer","Working","Sitting","Girl","Happy"]},
{"src":"images/People Emotions (online) (18)_12.webp","tags":["Looking","Front","People1","Standing","Boy","Talking","Happy"]},
{"src":"images/People Emotions (online) (18)_13.webp","tags":["Looking","Front","People1","Standing","Boy"]},
{"src":"images/People Emotions (online) (18)_14.webp","tags":["Looking","Front","People1","Standing","Boy","Baby"]},
{"src":"images/People Emotions (online) (18)_15.webp","tags":["Looking","Front","People1","Standing","Boy","Baby"]},
{"src":"images/People Emotions (online) (18)_16.webp","tags":["Looking","Front","People1","Standing","Boy"]},
{"src":"images/People Emotions (online) (18)_17.webp","tags":["Looking","Front","People1","Standing","Boy","Baby"]},
{"src":"images/People Emotions (online) (18)_18.webp","tags":["Looking","Front","People1","Standing","Baby"]},
{"src":"images/People Emotions (online) (18)_2.webp","tags":["Looking","Side‍","Front","People1","Standing","Boy"]},
{"src":"images/People Emotions (online) (18)_3.webp","tags":["Looking","Front","People1","Standing","Boy","Talking","Girl","Happy"]},
{"src":"images/People Emotions (online) (18)_4.webp","tags":["Looking","Front","People1","Standing","Boy","Talking","Girl"]},
{"src":"images/People Emotions (online) (18)_5.webp","tags":["Looking","Front","People1","Standing","Boy"]},
{"src":"images/People Emotions (online) (18)_6.webp","tags":["Looking","Front","People1","Standing","Girl"]},
{"src":"images/People Emotions (online) (18)_7.webp","tags":["Looking","Front","People1","Sitting","Boy"]},
{"src":"images/People Emotions (online) (18)_8.webp","tags":["Looking","Side‍","Front","People1","Standing","Girl"]},
{"src":"images/People Emotions (online) (18)_9.webp","tags":["Looking","Front","People1","Standing","Boy"]},
{"src":"images/People Emotions (online) (19)_1.webp","tags":["Looking","Front","People1","Loser","Boy","Baby"]},
{"src":"images/People Emotions (online) (19)_10.webp","tags":["Looking","Front","People1","Surprising","Confidence","Standing","Boy","Talking","Enjoy","Happy"]},
{"src":"images/People Emotions (online) (19)_11.webp","tags":["Looking","Front","People1","Surprising","Boy","Talking","Enjoy","Happy"]},
{"src":"images/People Emotions (online) (19)_12.webp","tags":["Looking","Front","People1","Standing","Boy","Talking","Enjoy"]},
{"src":"images/People Emotions (online) (19)_13.webp","tags":["Side‍","People1","Surprising","Confidence","Standing","Boy","Talking","Enjoy","Back"]},
{"src":"images/People Emotions (online) (19)_14.webp","tags":["People1","Surprising","Confidence","Standing","Boy","Talking","Enjoy","Back"]},
{"src":"images/People Emotions (online) (19)_15.webp","tags":["Looking","Side‍","Front","People1","Surprising","Confidence","Standing","Boy","Talking","Enjoy","Happy"]},
{"src":"images/People Emotions (online) (19)_16.webp","tags":["People1","Surprising","Confidence","Standing","Boy","Talking","Enjoy","Happy","Back"]},
{"src":"images/People Emotions (online) (19)_17.webp","tags":["People1","Standing","Talking","Girl","Enjoy","Happy"]},
{"src":"images/People Emotions (online) (19)_18.webp","tags":["Looking","Front","People1","Surprising","Standing","Boy","Talking"]},
{"src":"images/People Emotions (online) (19)_2.webp","tags":["Looking","Front","People1","Standing","Girl"]},
{"src":"images/People Emotions (online) (19)_3.webp","tags":["Looking","Front","People1","Standing","Girl","Enjoy"]},
{"src":"images/People Emotions (online) (19)_4.webp","tags":["Looking","Front","People1","Standing","Boy","Talking","Enjoy","Happy"]},
{"src":"images/People Emotions (online) (19)_5.webp","tags":["Looking","Old","Front","People1","Standing","Boy","Talking","Enjoy","Happy","See"]},
{"src":"images/People Emotions (online) (19)_6.webp","tags":["Looking","Old","Front","People1","Standing","Boy","Talking","Enjoy","Happy"]},
{"src":"images/People Emotions (online) (19)_7.webp","tags":["Looking","Front","People1","Surprising","Standing","Boy","Talking","Enjoy","Happy"]},
{"src":"images/People Emotions (online) (19)_8.webp","tags":["Looking","Front","People1","Standing","Boy","Talking","Enjoy"]},
{"src":"images/People Emotions (online) (19)_9.webp","tags":["Looking","Front","People1","Confidence","Standing","Boy","Enjoy"]},
{"src":"images/People Emotions (online) (20)_1.webp","tags":["People1","Surprising","Standing","Talking","Girl"]},
{"src":"images/People Emotions (online) (20)_10.webp","tags":["Front","People1","Loser","Standing","Boy","Cry"]},
{"src":"images/People Emotions (online) (20)_11.webp","tags":["Looking","Front","People1","Standing","Boy","Talking"]},
{"src":"images/People Emotions (online) (20)_12.webp","tags":["Looking","Front","People1","Surprising","Standing","Boy","Talking","Cry"]},
{"src":"images/People Emotions (online) (20)_13.webp","tags":["Front","People1","Computer","Working","Standing","Boy"]},
{"src":"images/People Emotions (online) (20)_14.webp","tags":["Looking","Front","People1","Thinking","Confused","Loser","Relaxed","Standing","Girl"]},
{"src":"images/People Emotions (online) (20)_15.webp","tags":["Looking","Front","People1","Thinking","Confused","Loser","Standing","Boy"]},
{"src":"images/People Emotions (online) (20)_16.webp","tags":["Looking","Front","People1","Confidence","Standing","Boy"]},
{"src":"images/People Emotions (online) (20)_17.webp","tags":["Looking","Front","People1","Thinking","Confused","Computer","Working","Boy"]},
{"src":"images/People Emotions (online) (20)_18.webp","tags":["Looking","Front","People1","Thinking","Confused","Loser","Standing","Boy"]},
{"src":"images/People Emotions (online) (20)_2.webp","tags":["People1","Surprising","Standing","Talking","Girl","Angry"]},
{"src":"images/People Emotions (online) (20)_3.webp","tags":["People1","Surprising","Talking","Girl","Angry","Baby"]},
{"src":"images/People Emotions (online) (20)_4.webp","tags":["Front","People1","Standing","Talking","Girl"]},
{"src":"images/People Emotions (online) (20)_5.webp","tags":["Looking","Front","People1","Surprising","Standing","Talking","Girl","Angry"]},
{"src":"images/People Emotions (online) (20)_6.webp","tags":["Looking","Front","People1","Surprising","Loser","Standing","Talking","Girl"]},
{"src":"images/People Emotions (online) (20)_7.webp","tags":["Looking","Front","People1","Surprising","Talking","Girl"]},
{"src":"images/People Emotions (online) (20)_8.webp","tags":["Front","People1","Standing","Girl"]},
{"src":"images/People Emotions (online) (20)_9.webp","tags":["Looking","Front","Surprising","Standing","Boy","Girl"]},
{"src":"images/People Emotions (online) (21)_1.webp","tags":["Looking","Front","People1","Confused","Standing","Girl"]},
{"src":"images/People Emotions (online) (21)_10.webp","tags":["Looking","Front","People1","Relaxed","Girl"]},
{"src":"images/People Emotions (online) (21)_11.webp","tags":["Looking","Front","People1","Standing","Boy"]},
{"src":"images/People Emotions (online) (21)_12.webp","tags":["Looking","Front","People1","Standing","Boy"]},
{"src":"images/People Emotions (online) (21)_13.webp","tags":["Looking","Old","Front","People1","Standing","Boy"]},
{"src":"images/People Emotions (online) (21)_14.webp","tags":["Old","Front","People1","Standing","Boy"]},
{"src":"images/People Emotions (online) (21)_15.webp","tags":["People1","Relaxed","Girl","Cry"]},
{"src":"images/People Emotions (online) (21)_16.webp","tags":["Old","Side‍","People1","Standing","Boy","Travel","Back"]},
{"src":"images/People Emotions (online) (21)_17.webp","tags":["Looking","Old","Front","People1","Boy"]},
{"src":"images/People Emotions (online) (21)_18.webp","tags":["Looking","Front","People1","Surprising","Girl","Cry"]},
{"src":"images/People Emotions (online) (21)_2.webp","tags":["Looking","Front","People1","Thinking","Confused","Standing","Boy"]},
{"src":"images/People Emotions (online) (21)_3.webp","tags":["Front","People1","Computer","Working","Girl"]},
{"src":"images/People Emotions (online) (21)_4.webp","tags":["Looking","Front","People1","Computer","Working","Standing","Boy"]},
{"src":"images/People Emotions (online) (21)_5.webp","tags":["Looking","Front","People1","Computer","Working","Sitting","Girl"]},
{"src":"images/People Emotions (online) (21)_6.webp","tags":["Looking","Front","People1","Boy"]},
{"src":"images/People Emotions (online) (21)_7.webp","tags":["Looking","Front","People1","Thinking","Confused","Working","Girl"]},
{"src":"images/People Emotions (online) (21)_8.webp","tags":["Looking","Front","People1","Thinking","Confused","Relaxed","Sitting","Boy"]},
{"src":"images/People Emotions (online) (21)_9.webp","tags":["Looking","Front","People1","Thinking","Confused","Computer","Relaxed","Boy"]},
{"src":"images/People Emotions (online) (22)_1.webp","tags":["Front","People1","Computer","Relaxed","Working","Boy","Sleep"]},
{"src":"images/People Emotions (online) (22)_10.webp","tags":["People1","Computer","Working","Standing","Boy"]},
{"src":"images/People Emotions (online) (22)_11.webp","tags":["Looking","Front","People1","Standing","Boy"]},
{"src":"images/People Emotions (online) (22)_12.webp","tags":["Looking","Front","People1","Standing","Boy"]},
{"src":"images/People Emotions (online) (22)_13.webp","tags":["Looking","Front","People1","Boy"]},
{"src":"images/People Emotions (online) (22)_14.webp","tags":["Looking","Front","People1","Boy"]},
{"src":"images/People Emotions (online) (22)_15.webp","tags":["Looking","Front","People1","Boy"]},
{"src":"images/People Emotions (online) (22)_16.webp","tags":["Looking","Front","People1","Boy"]},
{"src":"images/People Emotions (online) (22)_17.webp","tags":["Looking","Front","People1","Standing","Boy","Angry"]},
{"src":"images/People Emotions (online) (22)_18.webp","tags":["Looking","Front","People1","Confidence","Standing","Boy"]},
{"src":"images/People Emotions (online) (22)_2.webp","tags":["Looking","Front","People1","Loser","Standing","Girl","Cry"]},
{"src":"images/People Emotions (online) (22)_3.webp","tags":["Front","People1","Loser","Standing","Boy","Cry"]},
{"src":"images/People Emotions (online) (22)_4.webp","tags":["Front","People1","Loser","Girl","Cry"]},
{"src":"images/People Emotions (online) (22)_5.webp","tags":["Front","People1","Thinking","Confused","Loser","Relaxed","Sitting","Boy","Girl","Cry"]},
{"src":"images/People Emotions (online) (22)_6.webp","tags":["Front","People1","Loser","Standing","Girl","Cry"]},
{"src":"images/People Emotions (online) (22)_7.webp","tags":["Looking","Front","People1","Loser","Girl","Cry"]},
{"src":"images/People Emotions (online) (22)_8.webp","tags":["Looking","People1","Loser","Boy","Cry"]},
{"src":"images/People Emotions (online) (22)_9.webp","tags":["Old","Front","People1","Surprising","Boy","Cry"]},
{"src":"images/People Emotions (online) (23)_1.webp","tags":["Looking","Old","Front","People1","Boy","Talking"]},
{"src":"images/People Emotions (online) (23)_10.webp","tags":["Looking","Old","Front","People1","Boy"]},
{"src":"images/People Emotions (online) (23)_11.webp","tags":["Looking","Front","People1","Confidence","Standing","Boy"]},
{"src":"images/People Emotions (online) (23)_12.webp","tags":["Looking","Old","Front","People1","Standing","Boy"]},
{"src":"images/People Emotions (online) (23)_13.webp","tags":["Old","Front","People1","Standing","Boy"]},
{"src":"images/People Emotions (online) (23)_14.webp","tags":["Looking","Front","People1","Standing","Boy","See"]},
{"src":"images/People Emotions (online) (23)_15.webp","tags":["Looking","Front","People1","Standing","Boy","Talking","See"]},
{"src":"images/People Emotions (online) (23)_16.webp","tags":["Front","People1","Computer","Standing","Boy"]},
{"src":"images/People Emotions (online) (23)_17.webp","tags":["People1","Standing","Boy"]},
{"src":"images/People Emotions (online) (23)_18.webp","tags":["Looking","Front","People1","Standing","Boy"]},
{"src":"images/People Emotions (online) (23)_2.webp","tags":["Looking","Front","People1","Boy","Talking","Cry"]},
{"src":"images/People Emotions (online) (23)_3.webp","tags":["Looking","Front","People1","Confidence","Standing","Boy"]},
{"src":"images/People Emotions (online) (23)_4.webp","tags":["Looking","Front","People1","Standing"]},
{"src":"images/People Emotions (online) (23)_5.webp","tags":["Looking","Front","People1","Standing","Boy","Angry"]},
{"src":"images/People Emotions (online) (23)_6.webp","tags":["Looking","Front","People1","Standing","Girl"]},
{"src":"images/People Emotions (online) (23)_7.webp","tags":["Looking","Old","Front","People1","Boy","Angry"]},
{"src":"images/People Emotions (online) (23)_8.webp","tags":["Looking","Old","Front","People1","Standing","Boy","Angry"]},
{"src":"images/People Emotions (online) (23)_9.webp","tags":["Looking","Old","Front","People1","Standing","Boy","Angry"]},
{"src":"images/People Emotions (online) (24)_1.webp","tags":["Looking","Front","People1","Computer","Working","Girl"]},
{"src":"images/People Emotions (online) (24)_10.webp","tags":["Looking","Side‍","People1","Standing","Boy"]},
{"src":"images/People Emotions (online) (24)_11.webp","tags":["Looking","Old","Side‍","People1","Boy"]},
{"src":"images/People Emotions (online) (24)_12.webp","tags":["Looking","Old","Side‍","People1","Boy"]},
{"src":"images/People Emotions (online) (24)_13.webp","tags":["Looking","Front","People1","Standing","Girl"]},
{"src":"images/People Emotions (online) (24)_14.webp","tags":["People1","Confidence","Standing","Boy"]},
{"src":"images/People Emotions (online) (24)_15.webp","tags":["Looking","Front","Boy","Girl","People3"]},
{"src":"images/People Emotions (online) (24)_16.webp","tags":["Looking","Front","Standing","Boy","Girl","People3"]},
{"src":"images/People Emotions (online) (24)_17.webp","tags":["Looking","Front","Standing","Boy","Girl","People3"]},
{"src":"images/People Emotions (online) (24)_18.webp","tags":["Looking","Front","People2","Standing","Boy","Talking","Girl","Enjoy","Happy"]},
{"src":"images/People Emotions (online) (24)_2.webp","tags":["Looking","Front","People1","Standing","Girl"]},
{"src":"images/People Emotions (online) (24)_3.webp","tags":["Looking","Side‍","People1","Standing","Boy"]},
{"src":"images/People Emotions (online) (24)_4.webp","tags":["People1","Relaxed","Boy"]},
{"src":"images/People Emotions (online) (24)_5.webp","tags":["Looking","Front","People1","Standing","Girl"]},
{"src":"images/People Emotions (online) (24)_6.webp","tags":["Looking","Old","Side‍","Front","People1","Boy","Talking","See"]},
{"src":"images/People Emotions (online) (24)_7.webp","tags":["Looking","Front","People1","Standing","Boy","Baby"]},
{"src":"images/People Emotions (online) (24)_8.webp","tags":["Looking","Side‍","Front","People1","Confidence","Boy","Travel"]},
{"src":"images/People Emotions (online) (24)_9.webp","tags":["Looking","Front","People1","Boy","Cry"]},
{"src":"images/People Emotions (online) (25)_1.webp","tags":["Looking","Front","Confidence","Standing","Boy","Girl","People3"]},
{"src":"images/People Emotions (online) (25)_10.webp","tags":["Looking","Front","Standing","Boy","Girl","People3"]},
{"src":"images/People Emotions (online) (25)_11.webp","tags":["Looking","Front","Boy","Girl"]},
{"src":"images/People Emotions (online) (25)_12.webp","tags":["Looking","Old","Front","Standing","Boy","People3"]},
{"src":"images/People Emotions (online) (25)_13.webp","tags":["Looking","Front","Standing","Boy","Girl","People3"]},
{"src":"images/People Emotions (online) (25)_14.webp","tags":["Looking","Front","Standing","Boy","Girl","People3"]},
{"src":"images/People Emotions (online) (25)_15.webp","tags":["Looking","Front","Confidence","Standing","Boy","Girl","People3"]},
{"src":"images/People Emotions (online) (25)_16.webp","tags":["Front","Standing","Boy","Talking","Girl","People3"]},
{"src":"images/People Emotions (online) (25)_17.webp","tags":["Looking","Front","Boy","Girl","People∞"]},
{"src":"images/People Emotions (online) (25)_18.webp","tags":["Standing","Boy","Talking","Girl","People3"]},
{"src":"images/People Emotions (online) (25)_2.webp","tags":["Looking","Front","People2","Confused","Relaxed","Standing","Boy"]},
{"src":"images/People Emotions (online) (25)_3.webp","tags":["Looking","Front","People2","Boy"]},
{"src":"images/People Emotions (online) (25)_4.webp","tags":["Front","People2","Confused","Standing","Boy","Talking","Girl"]},
{"src":"images/People Emotions (online) (25)_5.webp","tags":["Front","Standing","Boy","Talking","Girl","People∞"]},
{"src":"images/People Emotions (online) (25)_6.webp","tags":["Looking","Front","Computer","Boy"]},
{"src":"images/People Emotions (online) (25)_7.webp","tags":["Looking","Old","Front","People2","Computer","Sitting","Boy","Girl"]},
{"src":"images/People Emotions (online) (25)_8.webp","tags":["People2","Loser","Standing","Boy"]},
{"src":"images/People Emotions (online) (25)_9.webp","tags":["People2","Standing","Boy"]},
// আরও ইমেজ যোগ করুন
];
// পেজিনেশন যুক্ত করে ইমেজ ডিসপ্লে ফাংশন
function displayImagesWithPagination() {
  const gallery = document.getElementById("image-gallery");
  gallery.innerHTML = ""; // পুরানো ইমেজ মুছে ফেলুন

  const filteredImages = images.filter(image =>
    selectedTags.length === 0 || selectedTags.every(tag => image.tags.includes(tag))
  );

  const startIndex = (currentPage - 1) * imagesPerPage;
  const endIndex = Math.min(startIndex + imagesPerPage, filteredImages.length);
  const imagesToShow = filteredImages.slice(startIndex, endIndex);

  imagesToShow.forEach((image) => {
    const imgElement = document.createElement("img");
    imgElement.src = image.src;
    imgElement.alt = "Image";
    imgElement.classList.add('resizable');
    gallery.appendChild(imgElement);
  });

  const paginationControls = document.createElement("div");
  paginationControls.className = "pagination-controls";

  if (currentPage > 1) {
    const prevButton = document.createElement("button");
    prevButton.textContent = "Previous";
    prevButton.onclick = () => {
      currentPage--;
      displayImagesWithPagination();
    };
    paginationControls.appendChild(prevButton);
  }

  if (endIndex < filteredImages.length) {
    const nextButton = document.createElement("button");
    nextButton.textContent = "Next";
    nextButton.onclick = () => {
      currentPage++;
      displayImagesWithPagination();
    };
    paginationControls.appendChild(nextButton);
  }

  gallery.appendChild(paginationControls);
}

// ইমেজ সাইজ পরিবর্তন করার ফাংশন
function resizeImages(size) {
  const images = document.querySelectorAll("#image-gallery img"); // সব ইমেজ নির্বাচন করুন
  images.forEach(img => {
    img.style.width = `${size}px`; // ইমেজের প্রস্থ পরিবর্তন
  });
}

// স্লাইডার ইভেন্ট লিসেনার যোগ করুন
document.getElementById("size-slider").addEventListener("input", function () {
  resizeImages(this.value); // স্লাইডারের মান অনুযায়ী ইমেজ সাইজ পরিবর্তন
});


// মাল্টিপল কিওয়ার্ড সিলেকশন সাপোর্ট
function toggleTag(tag) {
  const button = document.querySelector(`button[data-tag="${tag}"]`);

  if (selectedTags.includes(tag)) {
    // যদি ট্যাগ ইতিমধ্যে আছে, তাহলে তা সরান
    selectedTags = selectedTags.filter(t => t !== tag);
    button.classList.remove("selected"); // বাটন থেকে ক্লাস সরান
  } else {
    // নতুন ট্যাগ যোগ করুন
    selectedTags.push(tag);
    button.classList.add("selected"); // বাটনে ক্লাস যোগ করুন
  }

  currentPage = 1; // নতুন ট্যাগ সিলেক্ট হলে প্রথম পেজে যান
  displayImagesWithPagination();
}

// বাটন ক্লিক ইভেন্ট
function filterImages(tag) {
  toggleTag(tag); // ট্যাগকে টগল করুন
}

// ডিফল্টভাবে সব ইমেজ দেখান
displayImagesWithPagination();


// ডিফল্টভাবে সব ইমেজ দেখান
displayImagesWithPagination();
